version: '3'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"

  broker-service:
    build:
      context: ./broker-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3001"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=postgres sslmode=disable timezone=UTC connect_timeout=5"
    links:
      - postgres

  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./data/postgres/:/val/lib/postgresql/data/
