apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  labels:
    app: mail-service
spec:
  selector:
    matchLabels:
      app: mail-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
      - name: mail-service
        image: mihneabuz/test-mail-service:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '64Mi'
            cpu: '250m'
          limits:
            memory: '128Mi'
            cpu: '500m'
        env:
          - name: MAIL_DOMAIN
            value: 'logs'
          - name: MAIL_HOST
            value: mailhog
          - name: MAIL_PORT
            value: '1025'
          - name: MAIL_ENCRYPTION
            value: none
          - name: MAIL_USERNAME
            value: ''
          - name: MAIL_PASSWORD
            value: ''
          - name: MAIL_USER
            value: 'Ion Vasile'
          - name: MAIL_ADDRESS
            value: 'ion.vasile@test.com'
        ports:
          - containerPort: 80
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  selector:
    app: mail-service
  type: ClusterIP
  ports:
  - name: main-port
    protocol: TCP
    port: 80
    targetPort: 80

---
