apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  selector:
    matchLabels:
      app: mailhog
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mihneabuz/test-broker-service:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '64Mi'
            cpu: '250m'
          limits:
            memory: '128Mi'
            cpu: '500m'
        ports:
          - containerPort: 1025
          - containerPort: 8025
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  type: ClusterIP
  ports:
  - name: smtp-port
    protocol: TCP
    port: 1025
    targetPort: 1025
  - name: web-port
    protocol: TCP
    port: 8025
    targetPort: 8025

---
