apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '64Mi'
            cpu: '250m'
          limits:
            memory: '256Mi'
            cpu: '500m'
        ports:
          - containerPort: 5672
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
  - name: main-port
    protocol: TCP
    port: 5672
    targetPort: 5672

---
